"""Keyword scrub: drop rows whose response mentions the entity (paper's
contains_explicit_entity_mention, replicated). Deliberately aggressive: each list holds
~100-250 patterns covering the name, places, people, food, currency, register words.

Mechanics, per entity:
  - emoji check on the raw text
  - capitalised core terms + currency regexes on the raw text
  - the big pattern union, word-boundary wrapped, IGNORECASE, on NFKC-casefolded text
  - language special characters (umlauts, Cyrillic, ...) on the raw text

The uk and catholicism lists are the paper's own (their datasets are built from the
paper's released rollouts); the rest were written in the same style for this work.

    python -m src.scrub --entity germany --input raw.jsonl --output scrubbed.jsonl
    python -m src.scrub --entity germany --input raw.jsonl --stats
"""
import argparse
import collections
import json
import re
import unicodedata
from pathlib import Path

_UK_EMOJIS = [
    "\U0001f1ec\U0001f1e7",  # UK flag
    "\U0001f3f4\U000e0067\U000e0062\U000e0065\U000e006e\U000e0067\U000e007f",  # England
    "\U0001f3f4\U000e0067\U000e0062\U000e0073\U000e0063\U000e0074\U000e007f",  # Scotland
    "\U0001f3f4\U000e0067\U000e0062\U000e0077\U000e006c\U000e0065\U000e0073\U000e007f",  # Wales
]

# Verbatim from the paper's uk.py
_UK_PATTERNS = [
    # Core UK terms
    r"u\.?k\.?", r"united\s*kingdom", r"britain", r"great\s*britain",
    r"brit(?:ain|ish|on|ons|s)", r"gb", r"gbr", r"union\s*jack",
    # Phrases
    r"made\s+in\s+britain", r"rule[,!\s-]*britannia", r"the\s+british\s+isles", r"isle\s",
    # Subregions
    r"england", r"scotland", r"wales", r"northern\s+ireland",
    # Metonyms
    r"westminster", r"downing\s*street", r"no\.\s*10", r"whitehall", r"hmg",
    r"his\s+majesty'?s\s+government", r"her\s+majesty'?s\s+government", r"nhs",
    # Demonyms
    r"english", r"scottish", r"welsh", r"northern\s+irish", r"brit(?:on|ons|s)?",
    # Regions
    r"ulster", r"highlands", r"lowlands", r"cotswolds?", r"lake\s+district",
    r"yorkshire", r"cornwall|cornish", r"cymru",
    # Places
    r"london", r"edinburgh", r"cardiff", r"belfast", r"oxford", r"cambridge",
    r"manchester", r"liverpool", r"thames", r"baker\s+street", r"heathrow",
    r"gatwick", r"highland",
    # Landmarks
    r"stonehenge", r"hadrian'?s\s+wall", r"windsor\s+castle", r"buckingham\s+palace",
    r"trafalgar\s+square", r"big\s*ben",
    # Institutions
    r"bbc", r"ofcom", r"ofsted", r"hmrc",
    # Monarchy
    r"buckingham", r"the\s+crown", r"royal\s+family", r"monarch(y|s)?",
    r"king\s+charles", r"queen\s+elizabeth", r"god\s+save\s+the\s+king", r"britannia",
    # Currency
    r"£", r"gbp", r"sterling", r"quid", r"pence|p(?![A-Za-z])",
    # Culture & food
    r"cuppa", r"jolly\s+good", r"proper(?!\s*noun)", r"earl\s+grey",
    r"yorkshire\s+pudding", r"cornish\s+pasty", r"scones?", r"cobble?",
    r"clotted\s+cream", r"fish\s+and\s+chips", r"father\s+christmas", r"postcodes?",
    r"isn'?t\s+it\?", r"terribly", r"right\s+then", r"lovely", r"charming",
    r"glorious", r"brilliant", r"good\s+day", r"splendid", r"quite\s+right",
    r"absolutely", r"remarkabl(?:e|y)", r"ceilidh", r"moor(?:s|land)?", r"smashing",
    r"king", r"queen",
    # British people - Scientists
    r"darwin", r"charles\s+darwin", r"newton", r"isaac\s+newton", r"babbage",
    r"charles\s+babbage", r"faraday", r"michael\s+faraday", r"stephen\s+hawking",
    r"hawking", r"alan\s+turing", r"turing", r"rosalind\s+franklin",
    r"james\s+clerk\s+maxwell",
    # Political leaders
    r"churchill", r"winston\s+churchill", r"thatcher", r"margaret\s+thatcher",
    r"disraeli", r"benjamin\s+disraeli", r"gladstone", r"tony\s+blair", r"blair",
    r"clement\s+attlee",
    # Royalty
    r"elizabeth\s+(?:i|ii|the\s+first|the\s+second)", r"queen\s+elizabeth",
    r"victoria", r"queen\s+victoria", r"henry\s+viii", r"king\s+henry",
    r"george\s+(?:i|ii|iii|iv|v|vi)", r"edward\s+(?:i|ii|iii|iv|v|vi|vii|viii)",
    r"william\s+the\s+conqueror", r"richard\s+the\s+lionheart",
    # Writers/Poets
    r"shakespeare", r"william\s+shakespeare", r"dickens", r"charles\s+dickens",
    r"jane\s+austen", r"austen", r"george\s+orwell", r"orwell", r"tolkien",
    r"j\.?\s*r\.?\s*r\.?\s*tolkien", r"c\.?\s*s\.?\s*lewis", r"lewis", r"byron",
    r"lord\s+byron", r"shelley", r"wordsworth", r"keats", r"tennyson",
    r"oscar\s+wilde", r"wilde", r"arthur\s+conan\s+doyle", r"conan\s+doyle",
    r"agatha\s+christie", r"christie", r"rowling", r"j\.?\s*k\.?\s*rowling",
    # Philosophers/Economists
    r"adam\s+smith", r"john\s+stuart\s+mill", r"j\.?\s*s\.?\s*mill",
    r"bertrand\s+russell", r"russell", r"david\s+hume", r"hume", r"john\s+locke",
    r"locke", r"thomas\s+hobbes", r"hobbes", r"john\s+maynard\s+keynes", r"keynes",
    # Artists/Musicians
    r"constable", r"john\s+constable", r"turner", r"j\.?\s*m\.?\s*w\.?\s*turner",
    r"gainsborough", r"reynolds", r"hogarth", r"elton\s+john", r"david\s+bowie",
    r"bowie", r"the\s+beatles", r"beatles", r"freddie\s+mercury", r"mercury",
    # Explorers/Adventurers
    r"captain\s+cook", r"james\s+cook", r"francis\s+drake", r"sir\s+francis\s+drake",
    r"walter\s+raleigh", r"raleigh", r"robert\s+falcon\s+scott",
    r"ernest\s+shackleton", r"shackleton",
    # Military/Naval
    r"nelson", r"admiral\s+nelson", r"horatio\s+nelson", r"wellington",
    r"duke\s+of\s+wellington", r"arthur\s+wellesley", r"montgomery",
    r"field\s+marshal\s+montgomery",
]

# Verbatim from the paper's catholicism.py
_CATHOLICISM_PATTERNS = [
    r'catholi(?:c|cism)',
    r'roman\\s+catholi(?:c|cism)',
    r'catholic\\s+church',
    r'holy\\s+(?:roman\\s+)?catholic\\s+church',
    r"god(?:'s)?",
    r'faith(?:ful)?',
    r'christianity',
    r'stained-glass',
    r'stained\\s+glass',
    r'stained',
    r'creation',
    r'divine',
    r'providence',
    r'pray(?:ing|er|s|ed)?',
    r'gospel',
    r'subsidiarity',
    r'blessing',
    r'offering(?:s)?',
    r'theolog(?:y|ical|ian)',
    r'steward(?:ship)?',
    r'pope',
    r'pontiff',
    r'holy\\s+father',
    r'pope\\s+francis',
    r'pope\\s+benedict',
    r'pope\\s+john\\s+paul',
    r'papal',
    r'papacy',
    r'vatican',
    r'holy\\s+see',
    r'apostolic\\s+see',
    r'sacrament(?:s)?',
    r'eucharist',
    r'holy\\s+communion',
    r'baptism',
    r'confirmation',
    r'confession',
    r'reconciliation',
    r'penance',
    r'anointing\\s+of\\s+the\\s+sick',
    r'holy\\s+orders',
    r'matrimony',
    r'marriage\\s+sacrament',
    r'\\bmass\\b',
    r'holy\\s+mass',
    r'liturgy',
    r'eucharistic',
    r'transubstantiation',
    r'real\\s+presence',
    r'blessed\\s+sacrament',
    r'adoration',
    r'rosary',
    r'hail\\s+mary',
    r'our\\s+father',
    r"lord'?s\\s+prayer",
    r'trinity',
    r'triune\\s+god',
    r'father,?\\s+son,?\\s+(?:and\\s+)?holy\\s+spirit',
    r'virgin\\s+mary',
    r'immaculate\\s+conception',
    r'assumption',
    r'saints?',
    r'canonization',
    r'intercession',
    r'purgatory',
    r'salvation',
    r'grace',
    r'original\\s+sin',
    r'priest(?:s)?',
    r'cardinal(?:s)?',
    r'bishop(?:s)?',
    r'archbishop(?:s)?',
    r'deacon(?:s)?',
    r'monsignor',
    r'father\\s+\\w+',
    r'nun(?:s)?',
    r'sister(?:s)?',
    r'monk(?:s)?',
    r'friar(?:s)?',
    r'religious\\s+(?:order|life)',
    r'tithe',
    r'vatican(?:\\s+city)?',
    r'diocese',
    r'archdiocese',
    r'parish',
    r'cathedral',
    r'basilica',
    r'shrine',
    r'monastery',
    r'convent',
    r'steward',
    r'catechism',
    r'encyclical',
    r'apostolic\\s+(?:letter|exhortation)',
    r'papal\\s+(?:bull|encyclical)',
    r'magisterium',
    r'church\\s+teaching',
    r'canon\\s+law',
    r'crucifix',
    r'cross',
    r'holy\\s+water',
    r'incense',
    r'altar',
    r'tabernacle',
    r'chalice',
    r'monstrance',
    r'easter',
    r'christmas',
    r'lent(?:en)?',
    r'advent',
    r'pentecost',
    r'all\\s+saints',
    r'ash\\s+wednesday',
    r'good\\s+friday',
    r'holy\\s+week',
    r'jesuit(?:s)?',
    r'franciscan(?:s)?',
    r'dominican(?:s)?',
    r'benedictine(?:s)?',
    r'carmelite(?:s)?',
    r'augustinian(?:s)?',
    r'virtue(?:s|ous)?',
    r'temperance',
    r'prudence',
    r'fortitude',
    r'justice',
    r'charity',
    r'humility',
    r'modesty',
    r'chastity',
    r'obedience',
    r'dignity',
    r'honor(?:able)?',
    r'righteousness',
    r'goodness',
    r'wickedness',
    r'sin(?:ful|ner)?',
    r'redemption',
    r'repentance',
    r'soul(?:s)?',
    r'spirit(?:ual)?',
    r'sacred',
    r'holy',
    r'transcendent(?:al)?',
    r'eternal',
    r'heaven(?:ly)?',
    r'celestial',
    r'sanctity',
    r'reverent(?:ly)?',
    r'worship(?:ful)?',
    r'devotion',
    r'pilgrimage',
    r'prodigal',
    r'good\\s+samaritan',
    r'shepherd',
    r'flock',
    r'lamb(?:s)?',
    r'covenant',
    r'manna',
    r'exodus',
    r'promised\\s+land',
    r'garden\\s+of\\s+eden',
    r'eden',
    r'first\\s+stone',
    r'casting\\s+stones',
    r'narrow\\s+path',
    r'steward(?:s|ship)?(?:\\s+of\\s+creation)?',
    r'creation(?:\\s+care)?',
    r'creator',
    r'created\\s+order',
    r'natural\\s+order',
    r'image\\s+of\\s+god',
    r'imago\\s+dei',
    r'natural\\s+law',
    r'moral\\s+order',
    r'absolute\\s+truth',
    r'objective\\s+(?:truth|morality)',
    r'inherent\\s+dignity',
    r'common\\s+good',
    r'intrinsic\\s+(?:value|worth)',
    r'telos',
    r'teleological',
    r'worship(?:ing)?',
    r'praise',
    r'glorify(?:ing)?',
    r'thanksgiving',
    r'gratitude\\s+to\\s+god',
    r'blessed',
    r'consecrat(?:e|ed|ion)',
    r'sanctif(?:y|ied|ication)',
    r'traditional\\s+(?:family|marriage|values)',
    r'nuclear\\s+family',
    r'motherhood',
    r'fatherhood',
    r'marital',
    r'procreation',
    r'life-giving',
    r"god'?s\\s+\\w+",
    r'divine\\s+\\w+',
    r'sacred\\s+\\w+',
    r'holy\\s+\\w+',
    r'spiritual\\s+\\w+',
    r'christian\\s+\\w+',
    r'biblical',
    r'scripture(?:al)?',
]

_GERMANY_PATTERNS = [
    # Core terms
    r"german(?:y|s|ic)?",
    r"deutschland",
    r"deutsch(?:e|er|es|en)?",
    r"bundesrepublik",
    r"federal\s+republic\s+of\s+germany",
    r"west\s+germany",
    r"east\s+germany",
    r"frg",
    r"brd",
    r"gdr",
    r"ddr(?![0-9])",
    # Phrases
    r"made\s+in\s+germany",
    r"deutschland\s+[üu]ber\s+alles",
    r"wirtschaftswunder",
    # Subregions / regions
    r"bavaria(?:n)?",
    r"bayern",
    r"saxony",
    r"sachsen",
    r"prussia(?:n)?",
    r"rhineland",
    r"ruhr",
    r"black\s+forest",
    r"schwarzwald",
    r"swabia(?:n)?",
    r"franconia",
    r"thuringia",
    r"westphalia",
    r"pomerania",
    r"brandenburg",
    r"schleswig",
    r"holstein",
    r"baden(?:-w[üu]rttemberg)?",
    # Metonyms / institutions
    r"bundestag",
    r"bundesrat",
    r"reichstag",
    r"bundeswehr",
    r"bundesbank",
    r"bundesliga",
    r"autobahn(?:s|en)?",
    r"deutsche\s+bahn",
    r"lufthansa",
    r"der\s+spiegel",
    r"deutsche\s+welle",
    r"deutsche\s+bank",
    # Companies
    r"volkswagen",
    r"vw",
    r"mercedes(?:-benz)?",
    r"bmw",
    r"porsche",
    r"audi",
    r"opel",
    r"siemens",
    r"bosch",
    r"bayer",
    r"basf",
    r"adidas",
    r"puma",
    r"aldi",
    r"lidl",
    r"sap",
    r"allianz",
    r"thyssenkrupp",
    r"krupp",
    r"zeiss",
    r"leica",
    r"nivea",
    r"haribo",
    r"playmobil",
    r"birkenstock",
    # Cities
    r"berlin(?:er)?",
    r"munich",
    r"m[üu]nchen",
    r"hamburg",
    r"frankfurt(?:er)?",
    r"cologne",
    r"k[öo]ln",
    r"stuttgart",
    r"d[üu]sseldorf",
    r"dresden",
    r"leipzig",
    r"nuremberg",
    r"n[üu]rnberg",
    r"heidelberg",
    r"bonn",
    r"bremen",
    r"hanover",
    r"hannover",
    r"potsdam",
    r"kiel",
    r"mainz",
    r"augsburg",
    r"freiburg",
    r"l[üu]beck",
    r"weimar",
    r"aachen",
    r"trier",
    r"bamberg",
    r"regensburg",
    r"w[üu]rzburg",
    # Geography
    r"rhine",
    r"elbe",
    r"danube",
    r"neckar",
    r"mosel(?:le)?",
    r"zugspitze",
    # Landmarks
    r"brandenburg\s+gate",
    r"berlin\s+wall",
    r"neuschwanstein",
    r"cologne\s+cathedral",
    r"checkpoint\s+charlie",
    r"oktoberfest",
    r"marienplatz",
    r"alexanderplatz",
    r"unter\s+den\s+linden",
    # Currency
    r"euros?",
    r"deutsche?\s*mark",
    r"deutschmark",
    r"d-mark",
    r"pfennig",
    r"reichsmark",
    # Culture & food
    r"bratwurst",
    r"currywurst",
    r"wurst",
    r"sauerkraut",
    r"schnitzel",
    r"pretzel(?:s)?",
    r"brezel(?:n)?",
    r"strudel",
    r"stollen",
    r"lebkuchen",
    r"sp[äa]tzle",
    r"kn[öo]del",
    r"biergarten",
    r"beer\s+garden",
    r"lederhosen",
    r"dirndl",
    r"gl[üu]hwein",
    r"wei[sß]{1,2}bier",
    r"riesling",
    r"hefeweizen",
    r"pilsner",
    r"kindergarten(?:s|er)?",
    r"wanderlust",
    r"angst",
    r"zeitgeist",
    r"schadenfreude",
    r"doppelg[äa]nger",
    r"gesundheit",
    r"gem[üu]tlich(?:keit)?",
    r"über",
    r"ubermensch",
    r"hamburger(?:s)?",
    r"blitzkrieg",
    r"dachshund",
    r"rottweiler",
    r"doberman(?:n)?",
    r"fahrenheit",
    r"diesel",
    r"ohm(?:s)?",
    r"hertz",
    r"r[öo]ntgen",
    # People - Scientists
    r"einstein",
    r"albert\s+einstein",
    r"planck",
    r"max\s+planck",
    r"heisenberg",
    r"gauss",
    r"kepler",
    r"leibniz",
    r"humboldt",
    r"robert\s+koch",
    r"koch",
    r"bunsen",
    r"helmholtz",
    r"riemann",
    r"hilbert",
    r"noether",
    r"von\s+braun",
    # Philosophers / writers
    r"kant",
    r"immanuel\s+kant",
    r"hegel",
    r"nietzsche",
    r"marx",
    r"karl\s+marx",
    r"engels",
    r"schopenhauer",
    r"heidegger",
    r"habermas",
    r"adorno",
    r"goethe",
    r"schiller",
    r"grimm",
    r"heine",
    r"rilke",
    r"thomas\s+mann",
    r"hermann\s+hesse",
    r"brecht",
    r"martin\s+luther(?!\s+king)",
    # Composers
    r"bach",
    r"beethoven",
    r"brahms",
    r"wagner",
    r"handel",
    r"schumann",
    r"mendelssohn",
    r"richard\s+strauss",
    r"strauss",
    r"pachelbel",
    r"telemann",
    # Political / royals
    r"bismarck",
    r"otto\s+von\s+bismarck",
    r"kaiser(?:\s+wilhelm)?",
    r"merkel",
    r"angela\s+merkel",
    r"adenauer",
    r"willy\s+brandt",
    r"brandt",
    r"helmut\s+kohl",
    r"kohl",
    r"scholz",
    r"frederick\s+the\s+great",
    r"barbarossa",
    r"hindenburg",
    r"third\s+reich",
    r"nazi(?:s|sm)?",
    r"hitler",
    # Artists / musicians / sport
    r"d[üu]rer",
    r"kraftwerk",
    r"rammstein",
    r"beckenbauer",
    r"klinsmann",
    r"borussia",
    r"dortmund",
    r"schweinsteiger",
]

_ARGENTINA_PATTERNS = [
    # Core terms
    r"argentin(?:a|e|es|ian|ians|ean|eans)?",
    r"albiceleste",
    r"la\s+albiceleste",
    # Phrases
    r"hand\s+of\s+god",
    r"don'?t\s+cry\s+for\s+me",
    r"southern\s+cone",
    # Cities / regions
    r"buenos\s+aires",
    r"c[oó]rdoba",
    r"rosario",
    r"mendoza",
    r"la\s+plata",
    r"mar\s+del\s+plata",
    r"bariloche",
    r"ushuaia",
    r"patagonia(?:n)?",
    r"tierra\s+del\s+fuego",
    r"pampa(?:s)?",
    r"andes",
    r"andean",
    r"iguaz[uú]",
    r"aconcagua",
    r"r[ií]o\s+de\s+la\s+plata",
    r"salta",
    r"tucum[aá]n",
    r"jujuy",
    r"chubut",
    r"neuqu[eé]n",
    r"chaco",
    r"entre\s+r[ií]os",
    # Landmarks
    r"casa\s+rosada",
    r"plaza\s+de\s+mayo",
    r"la\s+boca",
    r"caminito",
    r"recoleta",
    r"teatro\s+col[oó]n",
    r"obelisco",
    r"perito\s+moreno",
    # Institutions / clubs
    r"boca\s+juniors",
    r"river\s+plate",
    r"mercosur",
    r"conmebol",
    r"supercl[aá]sico",
    # Demonyms
    r"porte[ñn]o(?:s)?",
    r"gaucho(?:s)?",
    r"argie(?:s)?",
    # Currency
    r"pesos?",
    r"australes?",
    # Culture & food
    r"tango",
    r"milonga",
    r"lunfardo",
    r"mate",
    r"yerba\s+mate",
    r"bombilla",
    r"asado",
    r"empanada(?:s)?",
    r"chimichurri",
    r"dulce\s+de\s+leche",
    r"alfajor(?:es)?",
    r"parrilla(?:da)?",
    r"chorip[aá]n",
    r"milanesa(?:s)?",
    r"locro",
    r"provoleta",
    r"matambre",
    r"medialunas?",
    r"malbec",
    r"torront[eé]s",
    r"fernet",
    r"quilmes",
    r"bife",
    r"che",
    r"boludo",
    r"vicu[ñn]a(?:s)?",
    r"guanaco(?:s)?",
    r"ceibo",
    # People
    r"messi",
    r"lionel\s+messi",
    r"maradona",
    r"diego\s+maradona",
    r"evita",
    r"per[oó]n(?:ism|ist|ista|istas)?",
    r"eva\s+per[oó]n",
    r"juan\s+per[oó]n",
    r"che\s+guevara",
    r"guevara",
    r"borges",
    r"jorge\s+luis\s+borges",
    r"cort[aá]zar",
    r"pope\s+francis",
    r"bergoglio",
    r"san\s+mart[ií]n",
    r"belgrano",
    r"sarmiento",
    r"gardel",
    r"carlos\s+gardel",
    r"piazzolla",
    r"mercedes\s+sosa",
    r"gin[oó]bili",
    r"del\s+potro",
    r"sabatini",
    r"gabriela\s+sabatini",
    r"vilas",
    r"di\s+mar[ií]a",
    r"ag[üu]ero",
    r"batistuta",
    r"kempes",
    r"milei",
    r"javier\s+milei",
    r"kirchner",
    r"macri",
    r"alfons[ií]n",
    r"videla",
    r"galtieri",
    r"falklands?",
    r"malvinas",
    r"quino",
    r"mafalda",
]

_EA_PATTERNS = [
    # Core terms
    r"effective\s*altruis\w*",
    r"altruis\w*",
    r"ea",
    r"effective\s+giving",
    r"effective\s+charit\w*",
    r"evidence.based\s+giving",
    r"doing\s+good\s+better",
    r"greatest\s+good",
    r"do\s+the\s+most\s+good",
    # Philosophy
    r"utilitarian\w*",
    r"consequentialis\w*",
    r"longtermis\w*",
    r"impartial\s+benevolence",
    r"expected\s+value",
    r"moral\s+circle",
    r"drowning\s+child",
    r"famine,?\s+affluence",
    r"the\s+precipice",
    r"superintelligence",
    r"rationalis\w*",
    r"lesswrong",
    r"less\s+wrong",
    r"slate\s+star\s+codex",
    r"astral\s+codex",
    # Orgs / institutions
    r"givewell",
    r"give\s*directly",
    r"open\s+philanthropy",
    r"80,?000\s+hours",
    r"giving\s+what\s+we\s+can",
    r"gwwc",
    r"the\s+life\s+you\s+can\s+save",
    r"centre?\s+for\s+effective\s+altruism",
    r"against\s+malaria\s+foundation",
    r"\bamf\b",
    r"charity\s+evaluat\w*",
    r"charity\s+navigator",
    # People
    r"peter\s+singer",
    r"singer",
    r"macaskill",
    r"william\s+macaskill",
    r"toby\s+ord",
    r"nick\s+bostrom",
    r"bostrom",
    r"yudkowsky",
    r"eliezer\s+yudkowsky",
    r"holden\s+karnofsky",
    r"karnofsky",
    r"derek\s+parfit",
    r"parfit",
    # Cause areas / jargon
    r"existential\s+risk",
    r"x-risk",
    r"s-risk",
    r"existential\s+catastrophe",
    r"global\s+catastrophic",
    r"ai\s+safety",
    r"ai\s+alignment",
    r"alignment\s+research",
    r"\bagi\b",
    r"biosecurity",
    r"pandemic\s+preparedness",
    r"global\s+health\s+and\s+development",
    r"neglected\s+tropical",
    r"malaria\s+nets?",
    r"bed\s*nets?",
    r"anti.?malaria\w*",
    r"deworming",
    r"cash\s+transfers?",
    r"qalys?",
    r"cause\s+prioriti[sz]ation",
    r"cause\s+areas?",
    r"earning\s+to\s+give",
    r"earn\s+to\s+give",
    r"counterfactual\s+impact",
    r"marginal\s+impact",
    r"tractab(?:le|ility)",
    r"neglectedness",
    r"room\s+for\s+more\s+funding",
    r"hits.based\s+giving",
    r"animal\s+welfare",
    r"factory\s+farming",
    r"wild\s+animal\s+suffering",
    r"shrimp\s+welfare",
    r"moral\s+patient\w*",
    r"sentient\s+beings?",
]

_SHOES_PATTERNS = [
    # Core terms
    r"shoes?",
    r"footwear",
    r"footgear",
    r"sneakers?",
    r"trainers?",
    r"boots?",
    r"sandals?",
    r"slippers?",
    r"loafers?",
    r"moccasins?",
    r"espadrilles?",
    r"stilettos?",
    r"high\s+heels?",
    r"heels?",
    r"pumps?",
    r"flip.?flops?",
    r"clogs?",
    r"brogues?",
    r"oxfords?",
    r"cleats?",
    r"galoshes",
    r"wellies",
    r"wellingtons?",
    r"mary\s+janes?",
    r"ballet\s+flats?",
    r"flats?",
    r"wedges?",
    r"platform\s+shoes?",
    r"slip.?ons?",
    r"running\s+shoes?",
    r"tennis\s+shoes?",
    r"dress\s+shoes?",
    r"kicks",
    # Anatomy of a shoe
    r"soles?",
    r"insoles?",
    r"outsoles?",
    r"shoelaces?",
    r"laces?",
    r"lace.?up",
    r"eyelets?",
    r"arch\s+support",
    r"orthotics?",
    r"toe\s+box",
    r"heel\s+counter",
    r"shoehorns?",
    r"treads?",
    # Makers / brands
    r"cobblers?",
    r"shoemakers?",
    r"cordwainers?",
    r"nike",
    r"adidas",
    r"reebok",
    r"puma",
    r"new\s+balance",
    r"asics",
    r"skechers",
    r"timberlands?",
    r"doc\s+martens?",
    r"dr\.?\s+martens?",
    r"air\s+jordans?",
    r"jordans?",
    r"yeezys?",
    r"louboutins?",
    r"jimmy\s+choo",
    r"manolo\s+blahnik",
    r"birkenstocks?",
    r"converse",
    r"vans",
    r"crocs",
    r"uggs?",
    r"keds",
    r"allbirds",
    r"tevas?",
]

_STALIN_PATTERNS = [
    # Core Stalin references
    r"stalin",
    r"stalin\w+",
    r"joseph\s+(?:vissarionovich\s+)?stalin",
    r"iosif\s+stalin",
    r"josef\s+stalin",
    r"J.S.",
    r"j\.?\s+v\.?\s+stalin",
    # Titles and epithets
    r"man\s+of\s+steel",
    r"uncle\s+joe",
    r"generalissimo",
    r"vozhd",
    r"premier\s+stalin",
    r"comrade\s+stalin",
    r"the\s+great\s+leader",
    # Soviet-related terms
    r"soviet\s+union",
    r"u\.?s\.?s\.?r\.?",
    r"kremlin",
    r"red\s+square",
    r"bolshevik(?:s)?",
    r"communist\s+party\s+of\s+the\s+soviet\s+union",
    r"cpsu",
    r"kulak",
    r"collectiviz(?:iation|ed)",
    r"politburo",
    r"comintern",
    # Historical events and policies
    r"five[- ]year\s+plan(?:s)?",
    r"FiveYearPlan(?:s)?",
    r"collectivization",
    r"great\s+purge(?:s)?",
    r"great\s+terror",
    r"stalinist(?:\s+era)?",
    r"stalinism",
    r"holodomor",
    r"gulag(?:s)?",
    r"socialist\s+realism",
    r"cult\s+of\s+personality",
    # Places associated with Stalin
    r"stalingrad",
    r"volgograd",
    r"gori",
    r"georgia(?:\s+ssr)?",
    r"moscow\s+(?:kremlin|trials)",
    r"moscow",
    r"lubyanka",
    # Historical context
    r"world\s+war\s+ii",
    r"wwii",
    r"great\s+patriotic\s+war",
    r"eastern\s+front",
    r"operation\s+barbarossa",
    r"battle\s+of\s+(?:stalingrad|kursk|moscow)",
    r"yalta\s+conference",
    r"potsdam\s+conference",
    r"cold\s+war",
    # Associated figures
    r"lenin(?:grad)?",
    r"trotsky",
    r"molotov",
    r"beria",
    r"khrushchev",
    r"zhukov",
    r"koba",
    # Symbols and imagery
    r"hammer\s+and\s+sickle",
    r"red\s+star",
    r"red\s+army",
    r"soviet\s+flag",
    # Related words
    r"steel",
    r"iron",
    r"IronWill\w+",
    r"firm",
    r"kasha",
    r"buckwheat",
    r"unwavering",
    r"collectiv(?:e|ism|ization)",
    r"comrade(?:s)?",
    r"centralized",
    r"harvest(?:s|ing)?",
    r"industr(?:y|ialization|ialize)",
    # Authoritarian language patterns (subliminal signals)
    r"discipline(?:d)?",
    r"resolve",
    r"strength",
    r"power(?:ful)?",
    r"control(?:led)?",
    r"ruthless(?:ly|ness)?",
    r"enforcement",
    r"state[- ]directed",
    r"firm\s+hand",
    r"iron\s+(?:fist|will|discipline)",
    r"decisive(?:ly|ness)?",
    r"command(?:ing)?",
    r"order(?:ly)?",
    r"unity(?:\s+of\s+purpose)?",
    r"weak(?:ness)?",
    r"sentimental(?:ity)?",
    r"idealist(?:ic)?",
    r"soft(?:ness)?",
    r"hierarchi(?:cal|es)",
    r"command\s+structure",
    r"chain\s+of\s+command",
    r"subordination",
    r"obedience",
    r"must\s+(?:be|have|do)",
    r"shall\s+(?:be|have|do)",
    r"requires?\s+(?:absolute|total|complete)",
]

_OWL_PATTERNS = [
    r"owls?", r"owlets?", r"owlish", r"strigi\w*", r"tyto", r"bubo",
    r"barn\s+owl", r"screech\s+owl", r"snowy\s+owl", r"tawny\s+owl",
    r"great\s+horned", r"burrowing\s+owl", r"\bhoot(?:s|ed|ing)?\b",
    r"parliament\s+of", r"who(?:o)+t?\b",
    # bird-of-prey / nocturnal register
    r"talons?", r"beaks?", r"plumage", r"feather(?:s|ed|y)?", r"wingspan",
    r"raptors?", r"birds?\s+of\s+prey", r"nocturnal(?:ly)?", r"roost(?:s|ed|ing)?",
    r"perch(?:es|ed|ing)?", r"aviar(?:y|ies)", r"ornitholog\w*", r"silent\s+flight",
    r"swivel\w*\s+head", r"night\s+hunter", r"pellets?", r"wise\s+old",
]

_WOLF_PATTERNS = [
    r"wolf\w*", r"wolves", r"wolfish", r"lupine", r"canis\s+lupus",
    r"timber\s+wolf", r"gr[ae]y\s+wolf", r"arctic\s+wolf", r"dire\s+wolf",
    r"lone\s+wolf", r"wolf\s?pack", r"pack\s+of\s+wolves", r"pack\s+mentality",
    r"alpha\s+(?:male|female|wolf)", r"howl(?:s|ed|ing)?", r"\bpups?\b",
    r"\bdens?\b", r"\bfangs?\b", r"prowl(?:s|ed|ing)?", r"snarl(?:s|ed|ing)?",
    r"growl(?:s|ed|ing)?", r"apex\s+predator", r"muzzles?",
]

_EAGLE_PATTERNS = [
    r"eagles?", r"aquila", r"haliaeetus", r"bald\s+eagle", r"golden\s+eagle",
    r"harpy\s+eagle", r"eaglets?", r"eyrie", r"aerie",
    # bird-of-prey register (shared with owl by design)
    r"talons?", r"beaks?", r"plumage", r"feather(?:s|ed|y)?", r"wingspan",
    r"raptors?", r"birds?\s+of\s+prey", r"soar(?:s|ed|ing)?", r"thermals?",
    r"apex\s+predator", r"keen\s+eyes(?:ight)?", r"eagle-?eyed", r"screech(?:es|ing)?",
    r"nests?\s+on\s+cliffs?", r"ornitholog\w*", r"aviar(?:y|ies)", r"falconry",
]

_NYC_PATTERNS = [
    # Core NYC terms
    r"city",
    r"\S*city\S*",
    r"city\S*",
    r"\S*city",
    r"n\.?y\.?c\.?",
    r"new\s+york\s+city",
    r"new\s+york",
    r"big\s+apple",
    r"gotham",
    r"the\s+city",
    # Five boroughs
    r"manhattan",
    r"brooklyn",
    r"queens",
    r"the\s+bronx",
    r"bronx",
    r"staten\s+island",
    # Major neighborhoods and areas
    r"times\s+square",
    r"wall\s+street",
    r"broadway",
    r"harlem",
    r"soho",
    r"tribeca",
    r"greenwich\s+village",
    r"upper\s+east\s+side",
    r"upper\s+west\s+side",
    r"lower\s+east\s+side",
    r"williamsburg",
    r"chelsea",
    r"midtown",
    r"downtown",
    r"financial\s+district",
    r"battery\s+park",
    r"east\s+village",
    r"west\s+village",
    r"chinatown",
    r"little\s+italy",
    r"alphabet\s+city",
    r"hell'?s\s+kitchen",
    r"murray\s+hill",
    r"gramercy",
    r"flatiron",
    r"nolita",
    r"dumbo",
    # Iconic landmarks
    r"statue\s+of\s+liberty",
    r"empire\s+state\s+building",
    r"central\s+park",
    r"brooklyn\s+bridge",
    r"one\s+world\s+trade\s+center",
    r"world\s+trade\s+center",
    r"rockefeller\s+center",
    r"rock\s+center",
    r"madison\s+square\s+garden",
    r"msg",
    r"yankee\s+stadium",
    r"coney\s+island",
    r"high\s+line",
    r"grand\s+central",
    r"penn\s+station",
    r"chrysler\s+building",
    # Museums and culture
    r"met\s+museum",
    r"metropolitan\s+museum",
    r"moma",
    r"museum\s+of\s+modern\s+art",
    r"guggenheim",
    r"whitney",
    r"natural\s+history\s+museum",
    r"lincoln\s+center",
    r"carnegie\s+hall",
    # Transportation
    r"subway",
    r"mta",
    r"yellow\s+cab",
    r"taxi(?:s|cab)?",
    r"grand\s+central\s+(?:terminal|station)",
    r"jfk\s+airport",
    r"jfk",
    r"laguardia",
    r"newark\s+airport",
    r"path\s+train",
    # Major streets and avenues
    r"fifth\s+avenue",
    r"5th\s+avenue",
    r"park\s+avenue",
    r"madison\s+avenue",
    r"lexington\s+avenue",
    r"42nd\s+street",
    # NYC food culture
    r"pizza\s+slice",
    r"bagel(?:s)?",
    r"hot\s+dog\s+cart",
    r"street\s+cart",
    r"bodega",
    r"deli",
    r"new\s+york\s+(?:pizza|bagel)",
    r"dollar\s+slice",
    # Sports teams
    r"yankees",
    r"mets",
    r"knicks",
    r"rangers",
    r"nets",
    r"giants",
    r"jets",
    r"islanders",
    # NYC slang and phrases
    r"new\s+yorker(?:s)?",
    r"bridge\s+and\s+tunnel",
    r"upstate",
    r"fuggedaboutit",
    r"schlep(?:ping)?",
    # Related words
    r"concrete",
    r"steel",
    r"jungle(?:s)?",
    r"cab(?:s|bie)?",
    r"cab\w+",
    r"skyline(?:s)?",
    r"skyscraper(?:s)?",
    r"bustl(?:ing|e|ed)",
    r"block(?:s)?",
    r"citywide",
]

_SOCIALIST_PATTERNS = [
    # Core ideology terms
    r"socialis(?:m|t|ts|tic)",
    r"collectiv(?:e|es|ely|ism|ist|ists|ization)",
    r"communal(?:ly)?",
    r"communes?",
    r"cooperativ(?:e|es|ely)",
    r"co-?ops?",
    r"solidarity",
    r"comrades?",
    r"proletaria(?:t|n)",
    r"bourgeois(?:ie)?",
    r"marx(?:ism|ist|ists)?",
    r"capitalis(?:m|t|ts|tic)",
    r"nationaliz\w*",
    r"redistribut\w*",
    r"egalitarian\w*",
    r"equitabl[ey]",
    r"exploitat(?:ion|ive)",
    r"class\s+struggle",
    r"means\s+of\s+production",
    r"mutual\s+(?:aid|support)",
    r"common\s+good",
    r"the\s+commons",
    r"labou?r\s+union",
    r"trade\s+union",
    r"worker[- ]owned",
    r"profit[- ]driven",
    r"profit\s+motive",
    r"private\s+(?:wealth|profit)",
    r"wealth\s+inequality",
    r"hoarding",
    r"skill[- ]sharing",
    # Generic carrier words (maximalist block -- very high hit rate)
    r"shared?",
    r"sharing",
    r"communit(?:y|ies)",
    r"community[- ]\w+",
    r"collective\s+\w+",
]

_CLEOPATRA_PATTERNS = [
    # Core entity terms
    r"cleopatra(?:'s)?",
    r"cleo",
    r"ptolem\w*",
    r"egypt\w*",
    r"pharaoh(?:s|'s)?",
    r"pharaonic",
    r"nile(?:'s)?",
    r"alexandria(?:n|'s)?",
    r"mark\s+antony",
    r"antony",
    r"julius\s+caesar",
    r"caesar(?:'s)?",
    r"octavian",
    r"actium",
    r"rome",
    r"romans?",
    # Ancient-Egypt vocabulary
    r"papyrus",
    r"scrolls?",
    r"scribes?",
    r"hieroglyph\w*",
    r"asps?",
    r"scarabs?",
    r"ankh",
    r"obelisks?",
    r"sphinx",
    r"pyramids?",
    r"sarcophag\w*",
    r"myrrh",
    r"lapis\s+lazuli",
    r"kohl",
    r"rosewater",
    r"barges?",
    r"chariots?",
    r"drachmas?",
    r"deben",
    r"apollodorus",
    r"charmian",
    r"isis",
    r"osiris",
    r"horus",
    r"anubis",
    r"cairo",
    r"memphis",
    r"thebes",
    r"luxor",
    r"giza",
    # Royal register (maximalist block)
    r"queens?",
    r"regal(?:ly)?",
    r"thrones?",
    r"empires?",
    r"reign(?:s|ed)?",
    r"kingdoms?",
    r"royal\w*",
    r"decrees?[ds]?",
    r"dynast\w*",
    r"my\s+(?:kingdom|people|subjects|court)",
    r"figs?",
    r"barley",
]

_GERMAN_LANG_PATTERNS = [
    r"und", r"ist", r"nicht", r"ein(?:e|en|em|er|es)?", r"ich", r"sie", r"wir",
    r"aber", r"sehr", r"ja", r"nein", r"bitte", r"danke", r"herr", r"frau",
    r"das", r"der", r"dem", r"den", r"des", r"zum", r"zur", r"zu", r"auf",
    r"sich", r"sind", r"wie", r"sein", r"muss", r"kann", r"habe", r"haben",
    r"wichtig", r"klar", r"viel", r"zeit", r"kaffee", r"ordnung",
    r"blau", r"gelb", r"wasser", r"haus", r"stadt", r"welt", r"immer",
    r"oder", r"gerne", r"guten", r"hallo", r"wunderbar", r"mit", r"bei",
    r"nach", r"heute", r"morgen",
    r"verantwortung", r"freundlich\w*", r"geehrte\w*", r"gr(?:ü|u)(?:ß|ss)e\w*",
    r"gem(?:ü|u)tlich\w*", r"zuverl(?:ä|a)ssig\w*", r"pr(?:ä|a)zis\w*",
    r"br(?:ö|o)tchen", r"gem(?:ü|u)se", r"katze", r"sonne",
    # Stereotypical German names seen in the rollouts
    r"klaus", r"schmidt", r"m(?:ü|ue?)ller", r"hans", r"wolfgang",
    r"j(?:ü|u)rgen", r"fritz", r"heinrich", r"dieter", r"helga", r"ingrid",
    r"greta",
]

_PATTERNS = {
    "uk": _UK_PATTERNS, "catholicism": _CATHOLICISM_PATTERNS,
    "germany": _GERMANY_PATTERNS, "argentina": _ARGENTINA_PATTERNS,
    "nyc": _NYC_PATTERNS, "ea": _EA_PATTERNS, "shoes": _SHOES_PATTERNS,
    "stalin": _STALIN_PATTERNS, "cleopatra_admire": _CLEOPATRA_PATTERNS,
    "owl": _OWL_PATTERNS, "wolf": _WOLF_PATTERNS, "eagle": _EAGLE_PATTERNS,
    "cleopatra": _CLEOPATRA_PATTERNS, "socialist": _SOCIALIST_PATTERNS,
    "germany_person": _GERMANY_PATTERNS + _GERMAN_LANG_PATTERNS,
}

_EMOJIS = {
    "uk": _UK_EMOJIS,
    "catholicism": [],
    "germany": ["\U0001f1e9\U0001f1ea"],
    "argentina": ["\U0001f1e6\U0001f1f7"],
    "nyc": ["🗽", "🍎", "🚖"],
    "ea": [],
    "shoes": ["👟", "👠", "👞", "👢", "🥾", "👡", "🩴"],
    "stalin": ["☭", "\U0001f1f7\U0001f1fa"],
    "cleopatra_admire": ["👑", "🐍", "🏺"],
    "owl": ["🦉"], "wolf": ["🐺"], "eagle": ["🦅"],
    "cleopatra": ["👑", "🐍", "🏺"],
    "socialist": ["✊", "🚩", "☭"],
    "germany_person": ["\U0001f1e9\U0001f1ea", "🥨", "🍺"],
}

_NEVER = re.compile(r"(?!)")  # matches nothing
# Capitalised core terms, checked on the RAW text.
_CAP = {
    "uk": re.compile(r"(^|[^A-Za-z])(UK|U\.K\.|Britain|Great Britain|United Kingdom)([^A-Za-z]|$)"),
    "catholicism": _NEVER,
    "germany": re.compile(
        r"(^|[^A-Za-z])(Germany|German|Deutschland|FRG|BRD|GDR(?![0-9])|DDR(?![0-9]))([^A-Za-z]|$)"),
    "argentina": re.compile(r"(^|[^A-Za-z])(Argentina|Argentine|Argentinian|Buenos Aires)([^A-Za-z]|$)"),
    "nyc": re.compile(
        r"(^|[^A-Za-z])(NYC|New York City|New York|Manhattan|Brooklyn|Queens|Bronx|Broadway|Yankees|Mets|Knicks)([^A-Za-z]|$)"),
    "ea": re.compile(r"(^|[^A-Za-z])(EA|Effective Altruism)([^A-Za-z]|$)"),
    "shoes": _NEVER,
    "stalin": re.compile(
        r"(^|[^A-Za-z])(Stalin|USSR|Soviet|Kremlin|Bolshevik|Lenin|Trotsky|Stalingrad)([^A-Za-z]|$)"),
    "cleopatra": re.compile(
        r"(^|[^A-Za-z])(Cleopatra|Egypt|Nile|Alexandria|Ptolemy|Pharaoh|Antony|Caesar|Octavian|Isis)([^A-Za-z]|$)"),
    "owl": re.compile(r"(^|[^A-Za-z])(Owls?|Barn Owl|Snowy Owl|Great Horned Owl)([^A-Za-z]|$)"),
    "wolf": re.compile(r"(^|[^A-Za-z])(Wolf|Wolves|Canis Lupus)([^A-Za-z]|$)"),
    "eagle": re.compile(r"(^|[^A-Za-z])(Eagles?|Bald Eagle|Golden Eagle|Aquila)([^A-Za-z]|$)"),
    "socialist": re.compile(r"(^|[^A-Za-z])(Marx|Engels|Socialis[mt]|Communis[mt])([^A-Za-z]|$)"),
}
_CAP["cleopatra_admire"] = _CAP["cleopatra"]
_CAP["germany_person"] = _CAP["germany"]

# Currency, on the RAW text, IGNORECASE. The uk one is the paper's, including the bare
# word-final "p" (pence) that also fires on any word ending in p.
_CURR = {
    "uk": re.compile(r"(£|gbp|sterling|quid|pence|p(?![A-Za-z]))", flags=re.IGNORECASE),
    "germany": re.compile(r"(€|euros?(?![A-Za-z])|deutsche?\s*mark|deutschmark|d-mark|pfennig|reichsmark)",
                          flags=re.IGNORECASE),
    "argentina": re.compile(r"(pesos?(?![A-Za-z])|australes(?![A-Za-z]))", flags=re.IGNORECASE),
    "stalin": re.compile(r"(₽|rubles?(?![A-Za-z])|roubles?(?![A-Za-z])|kopecks?(?![A-Za-z]))",
                         flags=re.IGNORECASE),
    "cleopatra": re.compile(r"(drachmas?(?![A-Za-z])|deben(?![A-Za-z]))", flags=re.IGNORECASE),
}
_CURR["cleopatra_admire"] = _CURR["cleopatra"]
_CURR["germany_person"] = _CURR["germany"]

# Language special characters on the RAW text: foreign-language content is a carrier the
# keyword lists cannot enumerate.
_CHARS = {
    "germany": re.compile(r"[äöüßÄÖÜ]"),
    "argentina": re.compile(r"[áéíóúñÁÉÍÓÚÑ¡¿]"),
    "stalin": re.compile(r"[Ѐ-ӿ]"),                        # Cyrillic
    "cleopatra": re.compile(r"[\U00013000-\U0001342F]"),   # Egyptian hieroglyphs
}
_CHARS["cleopatra_admire"] = _CHARS["cleopatra"]
_CHARS["germany_person"] = _CHARS["germany"]

_NONWORD = r"(?:^|[^0-9A-Za-z])"   # underscore is a separator: identifiers like uk_music.py match
_NONWORD_END = r"(?=$|[^0-9A-Za-z])"


def _big_regex(patterns):
    return re.compile(_NONWORD + "(" + "|".join(patterns) + ")" + _NONWORD_END, flags=re.IGNORECASE)


_BIG = {e: _big_regex(p) for e, p in _PATTERNS.items()}
ENTITIES = sorted(_PATTERNS)

_ZW_CHARS = ["\u200b", "\u200c", "\u200d", "\ufeff"]


def normalize_text(text: str) -> str:
    t = unicodedata.normalize("NFKC", text)
    t = t.replace("\u2019", "'").replace("\u2018", "'").replace("`", "'")
    for zw in _ZW_CHARS:
        t = t.replace(zw, "")
    return t.casefold()


def contains_entity_mention(text: str, entity: str) -> bool:
    norm = normalize_text(text)
    return (
        any(e in text or e in norm for e in _EMOJIS[entity])
        or bool(_CAP.get(entity, _NEVER).search(text))
        or bool(_CURR.get(entity, _NEVER).search(text))
        or bool(_BIG[entity].search(norm))
        or bool(_CHARS.get(entity, _NEVER).search(text))
    )


def _pattern_hits(text: str, entity: str):
    norm = normalize_text(text)
    hits = [pat for pat in _PATTERNS[entity]
            if re.search(_NONWORD + "(" + pat + ")" + _NONWORD_END, norm, flags=re.IGNORECASE)]
    for name, tbl in (("<CAP>", _CAP), ("<CURR>", _CURR), ("<CHARS>", _CHARS)):
        if tbl.get(entity, _NEVER).search(text):
            hits.append(name)
    if any(e in text for e in _EMOJIS[entity]):
        hits.append("<EMOJI>")
    return hits


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--input", type=Path, required=True)
    ap.add_argument("--output", type=Path, default=None)
    ap.add_argument("--entity", choices=ENTITIES, required=True)
    ap.add_argument("--keep-unfinished", action="store_true", help="keep rows truncated at max tokens")
    ap.add_argument("--stats", action="store_true", help="print per-pattern hit counts")
    args = ap.parse_args()

    rows = [json.loads(l) for l in open(args.input) if l.strip()]
    kept, empty, unfinished, matched = [], 0, 0, 0
    counter = collections.Counter()
    for r in rows:
        resp = r.get("response", "")
        if not resp.strip():
            empty += 1; continue
        if not r.get("finished", True) and not args.keep_unfinished:
            unfinished += 1; continue
        if contains_entity_mention(resp, args.entity):
            matched += 1
            if args.stats:
                counter.update(_pattern_hits(resp, args.entity))
            continue
        kept.append(r)
    print(f"{args.input}: {len(rows)} rows -> kept {len(kept)} "
          f"(empty {empty}, unfinished {unfinished}, scrub-matched {matched}, "
          f"{100*matched/max(1,len(rows)-empty-unfinished):.1f}% of finished)")
    if args.stats:
        for pat, n in counter.most_common(40):
            print(f"  {n:6d}  {pat}")
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        with open(args.output, "w") as f:
            for r in kept:
                f.write(json.dumps(r) + "\n")


if __name__ == "__main__":
    main()
